version: '1.0.{build}'

platform:
  - x64

cache:
  - node_modules -> package.json
  - app\node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: mIyDjFDU66Lari0Pbsttpt/41lYifTsf2fDUUh+X9T9AKCxh1AiW/Anj2LzagVUO

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off